FROM node:18 AS build

WORKDIR /app/frontend

# ENV REACT_APP_BACKEND_URL=http://backend:5000

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build


FROM nginx:alpine


COPY --from=build /app/frontend/build /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]