version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - FLASK_ENV=development
    networks:
      - chessnet

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    # environment:
    #   - REACT_APP_BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - chessnet
    # volumes:
    #   - ./frontend:/app/frontend

networks:
  chessnet:
    driver: bridge